# Generated by Django 6.1 on 2026-08-19 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Póliza')),
                ('policy_type', models.CharField(choices=[('HEALTH', 'Salud / Maternidad'), ('VEHICLE', 'Automóvil'), ('LIFE', 'Vida'), ('PROPERTY', 'Patrimonial')], default='HEALTH', max_length=20, verbose_name='Tipo de Cobertura')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto de Cobertura ($)')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('EXPIRED', 'Vencida'), ('SUSPENDED', 'Suspendida')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.CreateModel(
            name='InsuredProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='Cédula / DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asegurado',
                'verbose_name_plural': 'Asegurados',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True, verbose_name='Código de Reclamo')),
                ('incident_date', models.DateField(verbose_name='Fecha del Siniestro')),
                ('description', models.TextField(verbose_name='Descripción del Incidente')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Reclamado ($)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('IN_REVIEW', 'En Evaluación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado de Solicitud')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.insurancepolicy', verbose_name='Póliza')),
            ],
            options={
                'verbose_name': 'Siniestro / Reclamo',
                'verbose_name_plural': 'Siniestros / Reclamos',
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='claims.insuredprofile', verbose_name='Asegurado'),
        ),
    ]
