# Generated by Django 6.1 on 2026-08-19 17:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Nº Colegiado / Licencia')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(verbose_name='Motivo de Atención / Descripción'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Reclamado ($)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Atención'), ('IN_REVIEW', 'En Auditoría Médica'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado Solicitud'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Cobertura ($)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to='claims.doctorprofile', verbose_name='Médico Asignado'),
        ),
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_pressure', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Presión Alta (mmHg)')),
                ('low_pressure', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Presión Baja (mmHg)')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura (m)')),
                ('diagnosis_report', models.TextField(verbose_name='Informe Diagnóstico / Tratamiento')),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo del Servicio ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='claims.claim', verbose_name='Siniestro')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='claims.doctorprofile', verbose_name='Médico Tratante')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
            },
        ),
        migrations.CreateModel(
            name='PolicyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado ($)')),
                ('payment_reference', models.CharField(max_length=100, verbose_name='Número de Referencia')),
                ('receipt_file', models.FileField(upload_to='receipts/%Y/%m/', verbose_name='Comprobante (Imagen/PDF)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Verificación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado Verificación')),
                ('verification_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='claims.insurancepolicy', verbose_name='Póliza')),
            ],
            options={
                'verbose_name': 'Pago de Póliza',
                'verbose_name_plural': 'Pagos de Pólizas',
            },
        ),
    ]
