# Generated by Django 6.1 on 2026-08-19 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_doctorprofile_alter_claim_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Centro Médico')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.clinic', verbose_name='Clínica Atendente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio / Examen / Consulta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo Base / Baremo ($)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='claims.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Servicio de Clínica',
                'verbose_name_plural': 'Servicios de Clínicas',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='clinic_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.clinicservice', verbose_name='Servicio Requerido'),
        ),
        migrations.CreateModel(
            name='ClinicStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='claims.clinic', verbose_name='Clínica Asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepción')),
            ],
            options={
                'verbose_name': 'Personal de Recepción',
                'verbose_name_plural': 'Personal de Recepción',
            },
        ),
    ]
