# Generated by Django 6.1 on 2026-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_insuredprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
    ]
