# Generated by Django 6.1 on 2026-08-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_insuredprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('CONSULTATION', 'Consulta Médica'), ('XRAY', 'Rayos X / Imagenología'), ('LAB', 'Laboratorio / Exámenes'), ('OTHER', 'Otro Servicio')], default='CONSULTATION', max_length=30, verbose_name='Tipo de Servicio')),
                ('reason_or_symptoms', models.TextField(verbose_name='Motivo o Síntomas / Descripción')),
                ('notes_attachment', models.FileField(blank=True, null=True, upload_to='medical_requests/%Y/%m/', verbose_name='Récipe u Orden Médica (Opcional)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('SCHEDULED', 'Agendada'), ('REJECTED', 'Rechazada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20, verbose_name='Estado de la Solicitud')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de la Cita')),
                ('clinic_notes', models.TextField(blank=True, null=True, verbose_name='Observaciones de la Clínica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='claims.doctorprofile', verbose_name='Médico Asignado')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='claims.clinic', verbose_name='Clínica Destino')),
                ('clinic_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='claims.clinicservice', verbose_name='Servicio Específico del Baremo')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='claims.insuredprofile', verbose_name='Asegurado')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='claims.insurancepolicy', verbose_name='Póliza Utilizada')),
            ],
            options={
                'verbose_name': 'Solicitud de Cita / Servicio',
                'verbose_name_plural': 'Solicitudes de Citas y Servicios',
            },
        ),
    ]
