# Generated by Django 6.1 on 2026-08-24 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_medicalappointmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointmentrequest',
            name='insurance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Dictamen / Observaciones del Analista de Seguros'),
        ),
        migrations.AddField(
            model_name='medicalappointmentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Analista que Dictaminó'),
        ),
        migrations.AlterField(
            model_name='medicalappointmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Autorización (Seguros)'), ('SCHEDULED', 'Autorizada y Agendada'), ('REJECTED', 'Rechazada por Seguros'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado de la Solicitud'),
        ),
    ]
