# Generated by Django 6.1 on 2026-08-24 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_medicalappointmentrequest_insurance_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='medicalappointmentrequest',
            name='doctor_attachment',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/doctor/%Y/%m/', verbose_name='Récipe / Informe / Exámenes (Adjunto del Médico)'),
        ),
        migrations.AddField(
            model_name='medicalappointmentrequest',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio / Evolución Clínica'),
        ),
    ]
