# Generated by Django 6.1 on 2026-08-24 02:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_doctorprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en Catálogo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio Médico (Catálogo)',
                'verbose_name_plural': 'Catálogo de Servicios Médicos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_claim', to='claims.medicalappointmentrequest', verbose_name='Cita Origen'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RIF / Identificación Fiscal'),
        ),
        migrations.CreateModel(
            name='ClinicBaremo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio en esta Clínica ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremos', to='claims.clinic', verbose_name='Clínica')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremos', to='claims.medicalservice', verbose_name='Servicio del Catálogo')),
            ],
            options={
                'verbose_name': 'Baremo de Clínica',
                'verbose_name_plural': 'Baremos por Clínica',
                'unique_together': {('clinic', 'service')},
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='baremo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.clinicbaremo', verbose_name='Baremo Aplicado'),
        ),
    ]
