# Generated by Django 6.1 on 2026-08-24 04:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_migrate_legacy_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicbaremo',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Tarifa oficial en dólares americanos (USD). Se descuenta del saldo de la póliza.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio en esta Clínica (USD)'),
        ),
    ]
