# Generated by Django 6.1 on 2026-08-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_alter_clinicbaremo_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Siniestro / Reclamo', 'verbose_name_plural': 'Siniestros / Reclamos'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name'], 'verbose_name': 'Clínica', 'verbose_name_plural': 'Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='clinicbaremo',
            options={'ordering': ['clinic__name', 'service__name'], 'verbose_name': 'Baremo de Clínica', 'verbose_name_plural': 'Baremos por Clínica'},
        ),
        migrations.AlterModelOptions(
            name='clinicservice',
            options={'ordering': ['clinic', 'name'], 'verbose_name': 'Servicio de Clínica', 'verbose_name_plural': 'Servicios de Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='clinicstaffprofile',
            options={'ordering': ['id'], 'verbose_name': 'Personal de Recepción', 'verbose_name_plural': 'Personal de Recepción'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterModelOptions(
            name='insuredprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Asegurado', 'verbose_name_plural': 'Asegurados'},
        ),
        migrations.AlterModelOptions(
            name='medicalappointmentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Cita / Servicio', 'verbose_name_plural': 'Solicitudes de Citas y Servicios'},
        ),
        migrations.AlterModelOptions(
            name='medicalconsultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consulta Médica', 'verbose_name_plural': 'Consultas Médicas'},
        ),
        migrations.AlterModelOptions(
            name='policypayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago de Póliza', 'verbose_name_plural': 'Pagos de Pólizas'},
        ),
    ]
