# Generated by Django 6.1 on 2026-08-25 02:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_alter_claim_options_alter_clinic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fondo de Capital ($)')),
                ('pct_pago_clinica', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% de Pago a Clínicas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Financiera',
                'verbose_name_plural': 'Configuración Financiera',
            },
        ),
    ]
